version: "3"

services:
  mess_ws_front:
    build:
      context: ./front
      args:
        API_URL: ${API_URL}
    container_name: mess_ws_front
    command: serve -s build -l 3008
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    # before run cmd:  docker network create v1-network
    networks:
      - v1-network

  mess_ws_api:
    build: ./back
    container_name: mess_ws_api
    command: npm run start
    restart: unless-stopped
    environment:
      - API_PORT=${API_PORT}
      - TOKEN=${TOKEN}
      - CHAT=${CHAT}
    volumes:
      - ./logs:/usr/src/app/logs
    logging:
      options:
        max-size: 10m
    networks:
      - v1-network

networks:
  v1-network:
    external: true
